version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pkg/util/nethealth
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /test/kernel_log_generator
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /vendor/github.com/hpcloud/tail
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/go.opentelemetry.io/otel
    schedule:
      interval: daily
